apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1

# This helps with pod permissions later
iam:
  withOIDC: true

managedNodeGroups:
  - name: standard-nodes
    instanceType: t3.micro
    desiredCapacity: 3
    # IAM policies must be exactly these names
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
